### PR TITLE
added support for json.Marshaler interface

### PR DESCRIPTION
**Pull request by hooblei**
... would be great if goson supports the json.Marshaler interface as well

### CODE REVIEW

**Comment by emilsjolander** [comment]
i like it. I would however like to see a test that integrates this with structs that don't implement the interface. Maybe a test where a struct has a json.Marshaler as a field inside it.

**Comment by emilsjolander** [comment]
Please also edit the readme and mention that `json.Marshaler` is supported

**Comment by hooblei** [comment]
Hey, a bit late yesterday, so please burn the last one (9e348f0439528d9d87e4116a83688cdd8c8dcc4b) :)

The interface thing won't work like the way `valueForKey()` is implemented yet, e.g. for a value of `[]*time.Time` or `[]time.Time`, since one can not simple type switch on a slice of interface X (`[]json.Marshaler` or `[]*json.Marshaler`).

The question bubbled up, why is `valueForKey()` implemented that way instead of just using `json.Marshal()` on the requested value?
I have changed `valueForKey()` to use `json.Marshal()` and the tests run without a failure (eafd15470cc60b64aec0084545ff822a4039dff9) ... or I miss something?

**Comment by emilsjolander** [comment]
You are totally right. using `json.Marshal()` in `valueForKey()` is the correct solution. While testing and benchmarking this change i made the change myself (i was offline for a couple of days so could not pull new code).  So i'm closing this pull request but many thanks for the help!

**Pull request closed without merging**
